package lk.ijse.demokushan.Util;

public enum TextField {

    NAME, PASSWORD , CUSID, ADDRESS, EMAIL, PHONENUMBER,EID,POSITION,SALARY,COLOR,TIME,APID,HID,STYLE,PRICE,PID,QTYONHAND,PAID,TYPE,AMOUNT,SID,NIC
}
